### ISSUE TITLE
[1.19.2] Relics don't render on the player

### ISSUE THREAD

**Issue by PaulerLeOne** [SSKirillSS/relics#101]
Equipped relics don't render on the player. Before you ask, the curios slot display buttom hasn't been toggled off.

relics-1.19.2-0.4.7.1
curios-forge-1.192.-5.1.4.1

**Comment by SSKirillSS** [comment]
It's because relics don't have any render on the player.

**Comment by PaulerLeOne** [comment]
Then why do boots become hidden when I equip a relic in the feet slot?

**Comment by PaulerLeOne** [comment]
Oops, sorry, I thought something was meant to be rendered since armor pieces become hidden when wearing a relic.
