### ISSUE TITLE
Showing Twice In REI

### ISSUE THREAD

**Issue by DinnerBeef** [SSKirillSS/relics#102]
Most of the items are showing up twice in REI: 
![image](https://github.com/SSKirillSS/relics/assets/8346986/b911e0c4-d442-48b6-947a-91ce06288417)

Minecraft Version: 1.19.2
Forge Version: 43.2.14
Mod Version: 1.19.2-0.4.7.2

**Comment by SSKirillSS** [comment]
The official support for the mod on versions from 1.16.5 to 1.20.1 inclusive has been discontinued. However, the issue may be resolved by other users through a Pull Request.
