### ISSUE TITLE
Researching Table Recipe?

### ISSUE THREAD

**Issue by Aetrnl94** [SSKirillSS/relics#103]
Hi, I'm playing the most recent version of the mod with 1.20.1 Forge. I can't seem to find a recipe for the researching table. It's not showing up in JEI/EMI. Any guidance would be great. Thanks!

**Comment by SSKirillSS** [comment]
![image](https://github.com/SSKirillSS/relics/assets/38190325/361858c2-1a8b-44ac-8292-78ea2488265f)
