### ISSUE TITLE
[1.20.1] Relics Crash (Failed to load Piglin AI Mixin?)

### ISSUE THREAD

**Issue by Zedrimar** [SSKirillSS/relics#104]
Forge 47.1.3
Relics: 0.4.8.4
JEI: 15.2.0.27
Easy Piglins: 1.0.1
-OR-
Just Enough Resources: 1.4.0.238

It will crash with either easy piglins OR just enough resources. Same output on the crash log.

How to reproduce:
1. Load MC with those mods
2. Try to join a world
3. Profit....?

I didn't do a super deep dive, but I found a bit that showed it was something related to the piglin AI mixin. Everything seems to work as intended with the previous version of relics, however.

snippet I found:
`Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [relics.mixins.json:MixinPiglinAi] from phase [DEFAULT] in config [relics.mixins.json] FAILED during APPLY`

Full crash report here -> https://pastebin.com/NR8zaPfG

And another with the mixin in heaven mod for full mixin trace -> https://pastebin.com/d3b6p0gx

**Comment by Plite7067** [comment]
Someone has this problem as well - also has jer

**Comment by HockeyZman2000** [comment]
I think I'm getting a similar problem but it's this mod's PiglinAI conflicting with Big Brain.
[latest.log](https://github.com/SSKirillSS/relics/files/12478905/latest.log)

**Comment by SSKirillSS** [comment]
Seems like this issue should be resolved in [0.4.8.5](https://www.curseforge.com/minecraft/mc-mods/relics-mod/files/4733115) (at least I can't reproduce it now). Requires additional tests in a huge modpacks.

**Comment by Zedrimar** [comment]
Yep, fixed now. Thank you! :)
Also tried it with my mega pack of 415+ mods and works fine too.

**Comment by Plite7067** [comment]
nice, thank you!
