### ISSUE TITLE
[1.20.1] Infinity Ham cannot be used if equippable in Curios

### ISSUE THREAD

**Issue by TheIllusiveC4** [SSKirillSS/relics#108]
#### Versions:
* Relics: 0.5.1.4
* Curios: 5.4.5+1.20.1
* Forge/Fabric: 47.2.1
#### Observed Behavior:
If the Infinity Ham is tagged into a Curios slot such that it is equippable, it will no longer be useable as the equip behavior when right-clicked takes effect instead of the eating behavior.
#### Expected Behavior:
The Infinity Ham can be eaten while defined as a Curios item.
#### Steps to Reproduce:
1. Create a datapack and tag `relics:infinity_ham` into an available Curios slot.
2. Attempt to eat an Infinity Ham, but it will instead be equipped into the defined slot.

It looks like this is a result of the base `RelicItem` returning `true` for `ICurioItem#canEquipFromUse` but not overridden to be `false` for this particular item that has a separate use behavior. I'm not sure if this is the only one as I only tested one other item, the Shadow Glaive, which does not share this problem.

**Comment by SSKirillSS** [comment]
Should be fixed in the latest update.
