### ISSUE TITLE
Carry on incompatibility problem

### ISSUE THREAD

**Issue by GauntAndreX8** [SSKirillSS/relics#110]
it holds the table with the carry on when you try to use the table, could it be like not able to be pickable with tags?

**Comment by SSKirillSS** [comment]
Fixed in https://github.com/SSKirillSS/relics/commit/b8e481c8c380fd99dc74cfe2988ec5a54d6dbddc. Will be uploaded on CF with the next update.

**Comment by IIIap** [comment]
what about for 1.18.2?
