### ISSUE TITLE
Earthquake damage can create unkillable mobs

### ISSUE THREAD

**Issue by chj990707** [SSKirillSS/relics#111]
If you kill a monster by icebreaker's earthquake ability, the monster isn't killed, and becomes an unkillable mob. It can move and attack players normally, but doesn't show walking animation, can be hit by melee but not killed, cannot be hit by projectiles.
I am using the mod in the modpack Prominence II so other mods can be causing this.
To reproduce:
* Inflict mortal damage on a monster by using icebreaker earthquake ability.

**Comment by xelotex** [comment]
yEAH tHis stiLl HaPpens

**Comment by SSKirillSS** [comment]
Should not be an issue anymore (at least on 1.21 versions of the mod)
