### ISSUE TITLE
SUGGESTION - Update Tooltip After Research [1.19.2]

### ISSUE THREAD

**Issue by TrevorSlobodnick** [SSKirillSS/relics#112]
I noticed I get this message in the tooltip on a lot of relics - "You may learn more about this relic on the researching table". So naturally, I bring them to the researching table to learn more. Since my memory is pretty bad, I can't remember what any of these relics do, so I am constantly checking them over and over to remind myself.

I feel like it would be a great addition to the mod to update the tooltip with the actual description after viewing at the research table.

Thoughts?

**Comment by SiverDX** [comment]
are you using the latest version?

**Comment by TrevorSlobodnick** [comment]
MC Version - 1.19.2
Mod Version - 0.4.7.3

**Comment by SiverDX** [comment]
https://www.curseforge.com/minecraft/mc-mods/relics-mod/files/4779821

**Comment by TrevorSlobodnick** [comment]
Its working, thanks!

I just wanted to note that the mod on Modrinth for version 1.19.2 doesnt have version 0.4.7.4 as an option, which is why I used that one ^. Just incase you want to update it... 

Thanks again!

**Comment by SSKirillSS** [comment]
Done!
