### ISSUE TITLE
Quiver does not support tetra bows

### ISSUE THREAD

**Issue by haltalt** [SSKirillSS/relics#113]
1.20.1 forge. Ill update with more details once im back from Christmas.
I only tested one ability: the passive drawspeed increase. Making it work seems like a reasonably easy change since tetra adds an attribute for bow draw speed.

**Comment by SSKirillSS** [comment]
The official support for the mod on versions from 1.16.5 to 1.20.1 inclusive has been discontinued. However, the issue may be resolved by other users through a Pull Request.
