### ISSUE TITLE
Server crash with latest update

### ISSUE THREAD

**Issue by DelviousCrafts** [SSKirillSS/relics#116]
An attempt to load a client-only mixin class on server causes a startup crash in version 0.6. No crash report was generated. I verified this was due to Relics and not the OctoLib update.

[Latest Log](https://gist.github.com/DelviousCrafts/a21a6aa0cb7180f6e6a64e35fb16b3cd)

Versions: 
- Minecraft: 1.20.1
- Forge: 47.2.20
- Relics: 0.6
- OctoLib: 0.3
- Curios 5.7.0

**Comment by SSKirillSS** [comment]
Hi. This was already fixed. You may download latest build from [Modrinth](https://modrinth.com/mod/relics-mod/version/e9XgEMpq). Currently awaiting approval on CF.
