### ISSUE TITLE
[1.20.1] Crash when looking pages in REI

### ISSUE THREAD

**Issue by DivannKokos** [SSKirillSS/relics#118]
[crash-2024-02-18_19.00.00-client.txt](https://github.com/SSKirillSS/relics/files/14322333/crash-2024-02-18_19.00.00-client.txt)
<html><body><ul>
Mods (there are others in crash-report, but they are irrelevant, i've tested as well with only this set of mods, same thing):
	<li><a href="https://modrinth.com/mod/nfn13YXA">Roughly Enough Items (REI)</a> [12.0.684]</li>
	<li><a href="https://modrinth.com/mod/9s6osm5g">Cloth Config v10 API</a> [11.1.118]</li>
	<li><a href="https://modrinth.com/mod/lhGA9TYQ">Architectury</a> [9.1.13]</li>
	<li><a href="https://modrinth.com/mod/RH2KUdKJ">OctoLib</a> [0.3]</li>
	<li><a href="https://modrinth.com/mod/vvuO3ImH">Curios API</a> [5.7.0]</li>
	<li><a href="https://modrinth.com/mod/OCJRPujW">Relics</a> [0.6.1]</li>
	<li><a href="https://modrinth.com/mod/P0Mu4wcQ">Artifacts</a> [9.2.2]</li>
</ul></body></html>

**Comment by DivannKokos** [comment]
this does not happen with JEI, so i've guess for now i'm stuck with REI

**Comment by SSKirillSS** [comment]
Hi. Thanks for the report!

Should be fixed now. Uploaded on Modrinth rn and awaiting approval on CF.
