### ISSUE TITLE
Crash on 0.6.1.6 for 1.19.2

### ISSUE THREAD

**Issue by B-Wither** [SSKirillSS/relics#120]
[crash-2024-03-13_00.03.50-client.txt](https://github.com/SSKirillSS/relics/files/14574705/crash-2024-03-13_00.03.50-client.txt)
Got this crash after update.

**Comment by B-Wither** [comment]
Maybe because of incompatibility of new version with Arcane Abilities but not sure.

**Comment by SSKirillSS** [comment]
Yea. After this update Relics is not compatible with outdated addons anymore. So addons should update themselves to work with newer version of Relics.

**Comment by MrAlxart** [comment]
fixed for 0.1.8!
