### ISSUE TITLE
Using a stack of potions on Infinity Ham deletes the entire stack

### ISSUE THREAD

**Issue by SiverDX** [SSKirillSS/relics#121]
https://github.com/SSKirillSS/relics/blob/d75a686c9cc8d118ec754ae67c2498d2add67b56/src/main/java/it/hurts/sskirillss/relics/items/relics/InfinityHamItem.java#L230

stackable potions are quite common in modpacks

**Comment by SSKirillSS** [comment]
Done. Will be uploaded on CF with the next update. Thanks for report!

**Comment by SiverDX** [comment]
i think you might need to decrease the stack count as well
