### ISSUE TITLE
RAM Compat - Tendon Lump crash

### ISSUE THREAD

**Issue by CaptainPepperjack** [SSKirillSS/relics#123]
crashes when taking damage while wearing the tendon relic

[crash-2024-03-16_14.26.11-server.txt](https://github.com/SSKirillSS/relics/files/14625314/crash-2024-03-16_14.26.11-server.txt)

**Comment by SSKirillSS** [comment]
Should be fixed on the latest update of RAM-Compat. Lemme know if it works for you
