### ISSUE TITLE
issue with Scarab Talisman

### ISSUE THREAD

**Issue by pwigary** [SSKirillSS/relics#13]
The Scarab Talisman relic resets the player's speed but not the step high, when unequipping. But rejoining the world solves that however.

**Comment by pwigary** [comment]
Another small thing I found was that the Scarab Talisman and Ice Skates actually still grands speed when players are in air

**Comment by SSKirillSS** [comment]
This ability was removed in https://github.com/SSKirillSS/relics/commit/ff2170973846007c98eb2f50e6a95607085790c7
