### ISSUE TITLE
Crash on server- version 0.6.4

### ISSUE THREAD

**Issue by CrusaderRabbit** [SSKirillSS/relics#132]
With version relics-1.20.1-0.6.4 I have seen it client crash twice on servers. Crash reports attached
[crash-2024-04-15_23.06.15-client.txt](https://github.com/SSKirillSS/relics/files/14997529/crash-2024-04-15_23.06.15-client.txt)
[crash2.txt](https://github.com/SSKirillSS/relics/files/14997532/crash2.txt)

**Comment by AzeznLadyofFloof** [comment]
Having this too, after testing a new modpack. Not sure if it's the EXACT same crash but that line is there
(This is on 1.20.1-0.6.5 after the crash was fixed seems?)

[crash-2024-04-19_20.44.00-client.txt](https://github.com/SSKirillSS/relics/files/15046431/crash-2024-04-19_20.44.00-client.txt)

**Comment by SSKirillSS** [comment]
Should be fixed since 0.6.5.1
