### ISSUE TITLE
[1.21] Relics tries to download Curious for MC 1.20.6

### ISSUE THREAD

**Issue by NielsPilgaard** [SSKirillSS/relics#143]
Hi :wave:

I added Relics to my modpack through the Curseforge launcher, which prevented my game from loading, because it downloaded Curios for MC 1.20.6.

**Comment by SSKirillSS** [comment]
You need to download it [here](https://www.curseforge.com/minecraft/mc-mods/curios-continuation).

**Comment by NielsPilgaard** [comment]
Right, but I'm not going to ask players to download an additional mod manually, people are expecting mods to handle their own dependencies 😅

**Comment by SSKirillSS** [comment]
Well, I understand now. Yea, it's a bit bugged dependencies handling of CurseForge. Should be fixed now (I believe)

**Comment by NielsPilgaard** [comment]
Yup all good now, thank you 👍
