### ISSUE TITLE
Relic crashes on servers 1.21

### ISSUE THREAD

**Issue by TelepathicGrunt** [SSKirillSS/relics#144]
Migrating this issue report over to here since this appears to be a Relic bug: https://github.com/TelepathicGrunt/Bumblezone/issues/402

relevant exert: https://gist.github.com/NielsPilgaard/bf559f23e8acfad74ad2eed262dc2acc
latest.log: https://gist.github.com/NielsPilgaard/5c6dcf2f8bbfefd509195bcbdf014b52

 I do see this in the logs
`TRANSFORMER/relics@0.7.1/it.hurts.sskirillss.relics.system.casts.handlers.CacheHandler.onPlayerTick(CacheHandler.java:26`

From what i see, Relics is using a clientside class directly in common code. This will always crash servers.
https://github.com/SSKirillSS/relics/blob/d0e2196ce6c7139b61acac9c799548db43b8366c/src/main/java/it/hurts/sskirillss/relics/system/casts/handlers/CacheHandler.java#L26

Switch the check to `!level.isClient()` and you should be safe

**Comment by SSKirillSS** [comment]
Should be fixed now. Thanks for the info!
