### ISSUE TITLE
1.21 Researching Table visible in JEI/EMI but no crafting recipe

### ISSUE THREAD

**Issue by trunksbomb** [SSKirillSS/relics#145]
Not the same issue as reported in #103 - the item is visible in both JEI and EMI but cannot be crafted because there's no recipe.

![image](https://github.com/SSKirillSS/relics/assets/1904331/9a6388ca-4c43-4313-b4f9-1316df9574a1)
(Tried in a vanilla Crafting table as well, this one pictured is AE2)

![image](https://github.com/SSKirillSS/relics/assets/1904331/654e451d-0898-4274-9fa0-f40a8cf54363)

Forced a crash log here: https://mclo.gs/18MpKt8

**Comment by SSKirillSS** [comment]
Thanks for the info. Should be fixed now!
