### ISSUE TITLE
Compatibility issue with Cobbreeding mod

### ISSUE THREAD

**Issue by UnknownVariables-here** [SSKirillSS/relics#147]
Hey, didn't know which mod's issues section to put this into so posting on both. It seems that when relics is installed and grabbing an egg from the Cobblemon pasture block having the Cobbreeding mod installed (to allow the breeding mechanic) a server crash happens. This only happens on servers.

Client Latest Log: https://mclo.gs/pHoezVe

Server Latest Log: https://mclo.gs/ub0Vbgq

Server Crash Log: https://mclo.gs/cWdZvwF

What I did to reproduce this:
Make a test server and a test instance on Curseforge with Cobblemon and Cobbreeding and their dependencies.
add Relics mod.
Join server get 2 Cobblemon male and female put them in a PC.
Place a pasture block, open the gui and select the two Cobblemon.
Let them lay an egg takes about 5 minutes.
Right click to pickup the egg from the pasture block.

**Comment by SSKirillSS** [comment]
Hm... Seems like a compatibility issue with Forge. Can you try to reproduce this issue with latest NeoForge for 1.20.1?

**Comment by SSKirillSS** [comment]
Should be fixed now.
