### ISSUE TITLE
[1.21][relics-1.21-0.7.1.3] Can't add relics to the talisman slots

### ISSUE THREAD

**Issue by EmmaRavens** [SSKirillSS/relics#150]
Like the title says, can't add relics to the talisman slots that show up after adding the Drowned Belt

![Screenshot 2024-07-06 193923](https://github.com/SSKirillSS/relics/assets/12566399/f02953f2-5d67-4ef5-8ba5-8c7da673d6f3)
![Screenshot 2024-07-06 194156](https://github.com/SSKirillSS/relics/assets/12566399/31bbcd9b-dae1-472e-8853-8d3c097cb8b6)

**Comment by SSKirillSS** [comment]
"Talisman" - is a custom slot, that required for Spore Sack only atm (due to compat addons still didn't ported yet). We will remove it and switch to "Curio" slot instead in one of future major updates.
