### ISSUE TITLE
[1.20.1] Midnight Cape crash

### ISSUE THREAD

**Issue by tobi1449** [SSKirillSS/relics#156]
I'm running Minecraft 1.20.1 with Forge 47.2.20 and Relics 0.8.0.1

While wearing a Midnight Cape and when vanished, if I hit an enemy the server throws an `java.lang.ClassNotFoundException: net.minecraft.client.particle.TextureSheetParticle` ([full exception](https://gist.github.com/tobi1449/014b7adc3b8c8e8c92f925a9543f2395)) and kicks me. 

When trying to rejoin, I only get a `Connection Lost` ([full exception thrown on the server side](https://gist.github.com/tobi1449/9034c677ad4fe991870c0d86945701b5)) until I restart the server.

**Comment by SSKirillSS** [comment]
Hi! Thanks for the info. Update with fix should be on CurseForge in a few minutes. Lemme know if this (or any other) issue will appear to you.

**Comment by tobi1449** [comment]
Seems to be fixed, thanks :)
