### ISSUE TITLE
Broken Text

### ISSUE THREAD

**Issue by Mysandwich** [SSKirillSS/relics#157]
In the recent update for 1.20.1 version 0.8.0.1 the text for the Holy Locket's second ability is broken. [This was tested in a fresh instance with only Relics, Octolib, and Curios]

![image](https://github.com/user-attachments/assets/e0e25b81-cc1d-4bd4-bfc0-db00c2bdefa0)

**Comment by SyntaX0x** [comment]
Hello, it looks like MrAlxart_ didn't add translations for these values to the lang/en_us.json file, and possibly to other language files. I think this will be fixed very soon.

**Comment by SSKirillSS** [comment]
Fixed. Will be published to the CurseForge tomorrow. Also note that this update may reset leveling data of the Holy Locket, so it's not recommended to use this item in survival til the update.

![image](https://github.com/user-attachments/assets/b4827793-028d-47f7-8f40-72cac526c9e2)
