### ISSUE TITLE
Am stupid

### ISSUE THREAD

**Issue by CaptainNichols** [SSKirillSS/relics#159]
Hey , got a lil issue, i love your mod but don't know where in the config file the drop chances for the artifacts are, if someone could help out so i can put the mod in my modpack it would be very cool thank you for your time and sorry for using issues incorrectly don't know  where else to comment for this.

**Comment by SSKirillSS** [comment]
Hi. Afaik configs for loot chances are broken rn, so you can't change it. We are working on fixing this issue for 1.21 releases of Relics.

**Comment by CaptainNichols** [comment]
Tysm
