### ISSUE TITLE
1.20.1 Relics Crash

### ISSUE THREAD

**Issue by BritneyMc0206** [SSKirillSS/relics#175]
I'm playing on 1.20.1 with Forge 47.3.0.
I'm using Octolib 0.4.2 and Relics 0.8.0.7.

I tried playing with Relics installed, then Minecraft crashes when I load the game with an 'Exit Code: 1'
When Relics isn't installed, I'm able to play just fine, so I'm certain it's an incompatibility issue with something in my list.
I tried allocating 16000-22000 RAM, but both resulted in the same crash. (I have a total of 32000 RAM)

I didn't get a crash report, but I attached my latest log.
[latest.log](https://github.com/user-attachments/files/17265565/latest.log)

**Comment by SiverDX** [comment]
you will need to post your launcher log
(how you get it depends on your launcher)

here is an example for vanilla launcher:
https://minecrafthopper.net/help/guides/getting-minecraft-game-output-log/

**Comment by BritneyMc0206** [comment]
[launcher_log.txt](https://github.com/user-attachments/files/17266200/launcher_log.txt)
 I think this is it?

**Comment by SSKirillSS** [comment]
Looks like an incompatibility between octolib and mcpitanlib. Since it still didn't resolved, you need to choose which one mod you want to use.

**Comment by BritneyMc0206** [comment]
Ok thank you for the help!~ :D
