### ISSUE TITLE
Mahou tsuaki mental displacement crash

### ISSUE THREAD

**Issue by ziro-the-hutt** [SSKirillSS/relics#18]
When Relics is installed alongside Mahou Tsuaki the mental displacement spell crashes the game.
[crash-2021-06-15_09.24.19-client.txt](https://github.com/SSKirillSS/relics/files/6656115/crash-2021-06-15_09.24.19-client.txt)

**Comment by SSKirillSS** [comment]
Hi. Reflection Necklace HUD was removed in https://github.com/SSKirillSS/relics/commit/6400ed8e33e45d8ca34d6d082ebe5432ea7ed8de. So, this issue shouldn't appear again in the future versions.

But anyway, you should wait for the next update to get this fix.

**Comment by SSKirillSS** [comment]
Should be fixed in the 0.2.0 update.
