### ISSUE TITLE
Nightvision goggles Artifact mod/relics mod interaction issue

### ISSUE THREAD

**Issue by IonDrako** [SSKirillSS/relics#181]
Playing 1.6.1 update of craftoria and the Artifacts aspect of nightvision goggles get's completely overridden by the relics version completely removing the fact the goggles should at base give the night vision buff and are left with only turning everything green many ui elements included (which the world lighting is also ignored by shaders) which is arguably a much lesser version of the bauble.

**Comment by SSKirillSS** [comment]
Hi. Should not be an issue anymore, update your rar-compat version to the latest.
