### ISSUE TITLE
"hopper" ability shows up when holding alt

### ISSUE THREAD

**Issue by VaporeonScripts** [SSKirillSS/relics#183]
![image](https://github.com/user-attachments/assets/83bd06e3-d634-4190-bf75-61c5a25b0efd)

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/2f20ef4e-2228-49ea-8a36-382e96b40ca2)

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/e88126a1-b366-40ce-b4b7-9ad7208ce414)

**Comment by SSKirillSS** [comment]
The issue may be related to incorrectly reloading the game assets. Make sure you have the latest version of the mod installed and just restart the game. If the problem persists, reopen the issue with the following details: which modpack you're using (if it's a public modpack, just the name is enough; if not, provide a list of mods), which versions of Relics, OctoLib, and RAR-Compat you're using, and whether the issue appeared immediately or wasn't present before

**Comment by VaporeonScripts** [comment]
I use latest version of everything ,NeoTech Reborn modpack,idk if it was present before

**Comment by Temulla** [comment]
Hello! Thanks for the information, there really is a problem, it will be fixed in the next update!

**Comment by VaporeonScripts** [comment]
Alright!!!tyy

**Comment by VaporeonScripts** [comment]
btw this happens with every ability, compression too, the background is purple and black (typical texture error )
