### ISSUE TITLE
[Crash] Concurrent Modification Exception

### ISSUE THREAD

**Issue by pietro-lopes** [SSKirillSS/relics#187]
Steps to reproduce:

Download this world (place in your dev env folder, `runs/client/save/`):
https://drive.google.com/file/d/1ffQAupncHXFvz-Syhd-AYzCcepIrrXau/view?usp=drive_link

Summon silverfish
Wait a few hits
Teleport to Nether to unload those chunks

(video I did the opposite (Nether -> OW) but works the same)

https://github.com/user-attachments/assets/2a693966-4954-44de-af15-f84dda011e11

This is caused by this
<https://github.com/Octo-Studios/relics/blob/d63359a3ca25dfa837523d91219fac5ea498e9a0/src/main/java/it/hurts/sskirillss/relics/entities/SporeEntity.java#L134>

More specifically this:
<https://github.com/Octo-Studios/relics/blob/d63359a3ca25dfa837523d91219fac5ea498e9a0/src/main/java/it/hurts/sskirillss/relics/entities/SporeEntity.java#L181>

Here is a log from a mod I used to be able to LOG and capture where this CME was coming from:
<https://mclo.gs/l12cAnN#L4479>

**Comment by SSKirillSS** [comment]
Hi. Thanks for the info. Should be fixed since 1.21-0.9.2.1 release.
