### ISSUE TITLE
Relics has failed to load correctly 1.20.1

### ISSUE THREAD

**Issue by teapotmanagement** [SSKirillSS/relics#194]
mc version: 1.20.1
Forge: 47.1.3
mods:
alexscaves-2.0.2
architectuy-9.2.14
bluprint-1.0.0
citadel-2.6.0
connector-1.0.0-beta.46
continuity-3.0.0
curios-5.11.0
embeddium-0.3.31
ffapi-0.92.2
octolib-0.4.2
relics-0.8.0.7
![failed](https://github.com/user-attachments/assets/0f783731-35ab-49d5-ad3e-811504a2329a)
latest log: https://mclo.gs/uSZqCBC
crash log: https://mclo.gs/a2lRRB8

**Comment by SSKirillSS** [comment]
Looks like an outdated Forge version. Just update.

**Comment by teapotmanagement** [comment]
which forge version is supported? Just, synitra requires 47.1.3 fml version (recommend). Maybe change is possible

**Comment by SSKirillSS** [comment]
47.1.7 and higher
