### ISSUE TITLE
Researching table removed

### ISSUE THREAD

**Issue by Castle2501** [SSKirillSS/relics#195]
So the things is that my friends and I are using the Craftoria modpack and we are trying to use the relics mod but the table says [Removed from the mod]

![2024-12-26_19 39 09](https://github.com/user-attachments/assets/d7fa8f23-235c-4667-86b4-a76afd650322)

**Comment by SSKirillSS** [comment]
Hello. You don't need Researching Table for upgrading relics. Holding shift above the item will be enough.
