### ISSUE TITLE
crazy growth of log when equipped Ice Breaker 

### ISSUE THREAD

**Issue by Tidy-Bear** [SSKirillSS/relics#22]
When equipped Ice Break, latest.log will be filled with:
[Render thread/INFO] [STDOUT/]: [it.hurts.sskirillss.relics.items.relics.boots.IceBreakerItem:curioTick:60]: -0.1

It's seemed that you forget to remove the code for debug .
https://github.com/SSKirillSS/relics/blob/master/src/main/java/it/hurts/sskirillss/relics/items/relics/boots/IceBreakerItem.java#L60

**Comment by SSKirillSS** [comment]
Thanks for the info. Fixed in https://github.com/SSKirillSS/relics/commit/149647cc88efbe4ae03cbb94b317373505f251d1 and can be downloaded [here](https://www.curseforge.com/minecraft/mc-mods/relics-mod/files/3366542).
