### ISSUE TITLE
Disconnet from server when equipped Blazing Flask

### ISSUE THREAD

**Issue by Tidy-Bear** [SSKirillSS/relics#23]
The wearere equipped Blazing Flask may disconnect from dedicated server, showing msg of 'Internal Server Error'.

relevant log from server: https://paste.ubuntu.com/p/vcQmxGDwSx/

https://github.com/SSKirillSS/relics/blob/149647cc88efbe4ae03cbb94b317373505f251d1/src/main/java/it/hurts/sskirillss/relics/items/relics/BlazingFlaskItem.java#L119

ClientPlayerEntity does not exist on dedicated server, so check the side before using it.

**Comment by SSKirillSS** [comment]
Will be fixed in the next official update. In case you need it for server with custom client - you can join mod Discord and ping me, I'll send you a fixed version.

**Comment by SSKirillSS** [comment]
Should be fixed in https://github.com/SSKirillSS/relics/commit/c40fc1a68fce6f471ac4b25a4c956a446b07565e

Download will be available on the curseforge when update fill be fully finished.
