### ISSUE TITLE
Server crashed after the Wither Skeleton was directly killed by the effect of'reflection necklace'

### ISSUE THREAD

**Issue by Cherishhhhh** [SSKirillSS/relics#24]
I'm not sure if it only works on the wither skeleton,didn't test ohter entries.

**Comment by SSKirillSS** [comment]
Can't reproduce this issue. More info needed.

**Comment by Febilian** [comment]
I have reason to believe this is still a problem. I have had it occur with players off and on for a few weeks now and have been struggling to determine the cause. It has been with both normal and wither skeletons. After discussing, we have realized that the player who keeps triggering the crash has indeed been using the reflection amulet this entire time.

Here is the server crash log. This is in a setting with other mods, but it's better than having no crash log at all I suppose?

https://gist.github.com/Febilian/bee7f441cf2da66caad1ecbecba3d086
