### ISSUE TITLE
issue with blazing flask item (Bug)

### ISSUE THREAD

**Issue by Naues** [SSKirillSS/relics#31]
The blazing flask completely prevents me from taking fall damage and still allows me to sprint when I have less than 3 hunger bars. 
I removed all other mods I currently had excluding optifine, and tried replicating the issue. Doing this ended up with the same results. If the flask has no fire amount or is unequipped, everything goes back to normal until it it reequipped.

**Comment by SSKirillSS** [comment]
This is not a bug anymore since https://github.com/SSKirillSS/relics/commit/ff2170973846007c98eb2f50e6a95607085790c7
