### ISSUE TITLE
Holy Locket prevents invulnerability time from being bypassed

### ISSUE THREAD

**Issue by Ultimushadow** [SSKirillSS/relics#32]
When used with Dungeons Gear specifically, it became clear that many weapons from Dungeons Gear (eg fighter's bindings, corrupted beacon) that are meant to bypass invulnerability no longer function as intended. Seeing as the Cross Necklace from Artifacts, which has the same function as the Holy Locket, does work with these weapons, I assume this is due to how the Holy Locket itself functions and not the weapons.

**Comment by SSKirillSS** [comment]
Added in https://github.com/SSKirillSS/relics/commit/ff2170973846007c98eb2f50e6a95607085790c7

Wait til the next release.
