### ISSUE TITLE
Relics 0.2.4 feet slot relic incompatibility with cosmetic armor

### ISSUE THREAD

**Issue by Kutomi1** [SSKirillSS/relics#34]
equipping a curio in the feet slot while having the cosmetic armor mod causes the player's boots to become invisible and makes the boots slot look like it's empty

**Comment by SSKirillSS** [comment]
Should be fixed in the [0.2.5 release](https://www.curseforge.com/minecraft/mc-mods/relics-mod/files/3418886).
