### ISSUE TITLE
Infinity Ham sets hunger rather than adding hunger

### ISSUE THREAD

**Issue by Jackiecrazy** [SSKirillSS/relics#36]
Under default settings, each use of the infinity ham will set your hunger to 10 (5 shanks) instead of refilling hunger. Perhaps useful when starving, but not particularly helpful in other occasions.

**Comment by SSKirillSS** [comment]
Yea, my bad. Will be fixed in the next update. Thanks for the info!

**Comment by SSKirillSS** [comment]
Should be fixed now. You can download it [here](https://www.curseforge.com/minecraft/mc-mods/relics-mod/files/3427184).
