### ISSUE TITLE
[question] What is your intention with Runes, scraps, ingots, crystals, parchments etc?

### ISSUE THREAD

**Issue by Darkmega18** [SSKirillSS/relics#37]
I've gradually seen more and more of these special resources being created over my usage of the mods and making of my pack with the mod included.

Will there eventually be uses for these bits and pieces throughout the mod with the crafting mechanic that currently only has the boots and runes being craftable with the old boot? Or are some of these resources included as bits and pieces useable by modpack makers for their own shenanigans?

**Comment by SSKirillSS** [comment]
Hello. Yep. I'm slowly working on adding more uses to existed systems and items. atm my plan looks like this:
1. Better contract mechanic
2. Relics durability logic
3. Relics crafting logic
4. Relics leveling logic

Most entries in the list above already implemented, but still don't have good use. I'm working on it

**Comment by Darkmega18** [comment]
oh, you're gonna have relic leveling? like improving their functionality/having their functionality be more open? since I notice a lot of the relics have, uh, "novel use circumstances". 

and whats this contract mechanic? is it to do with how the relics by default lock themselves to the player? (I turned that off in my pack tho.)

**Comment by SSKirillSS** [comment]
Yep. Leveling will affect stats of relics and active abilities tiers.

Contracts - simple multiplayer only mechanic atm (in the future it will affect singleplayer too). For now, it prevents picking up relic with attached contract by other player (like on Botania, but without actually damage). Also notice that contracts works only for 1 hour after attaching. After this time, you should attach another contract to continue protect your relic.

**Comment by SSKirillSS** [comment]
Seems like it can be closed now due to moving into the Discord server.

**Comment by Darkmega18** [comment]
aye. :)
