### ISSUE TITLE
Bastion Ring miss spelling

### ISSUE THREAD

**Issue by LinJonKur** [SSKirillSS/relics#47]
In the Bastion Ring's description at Piggy Compass it says "Piblins" instead of "Piglins"

**Comment by SSKirillSS** [comment]
Hey. Thanks for the info. This issue already fixed (https://github.com/SSKirillSS/relics/commit/346ca7099029d37f73a5f16648f41a51008bca07) and fix will be implemented in the next major release.

**Comment by SSKirillSS** [comment]
o/

It's released and can be downloaded **[here](https://www.curseforge.com/minecraft/mc-mods/relics-mod/files/3586732)**!
