### ISSUE TITLE
Relics + Ender chest from EnderChests mod crashes and corrupts world

### ISSUE THREAD

**Issue by starmun-0010** [SSKirillSS/relics#48]
**Description**
Having an ender chest from [EnderChests](https://www.curseforge.com/minecraft/mc-mods/enderchests) mod in player's inventory instantly causes  a crash. You no  longer can join the world afterwads. Removing Relics or EnderChests mod fixes the issue.
Crash report has stack trace for Relics mod only, if this is an issue on EnderChest's side, please let me know.

**Steps to reproduce**
1. Install both Relics and EnderChests
2. Spawn or craft an ender chest.

**Crash Report**
[crash-2021-12-21_00.38.44-server.txt](https://github.com/SSKirillSS/relics/files/7747624/crash-2021-12-21_00.38.44-server.txt)

**Comment by SSKirillSS** [comment]
Hi. Seems like this is because of similar NBT tag name with Relics and Enderchests mods. It can be fixed on both sides, one mod just should change tag name to any other.

Relics will change it in the next major update.

**Comment by SSKirillSS** [comment]
Hey. You can try to use it with **[this version](https://www.curseforge.com/minecraft/mc-mods/relics-mod/files/3586732)**. It shouldn't crash anymore, but it's still not a fix.
