### ISSUE TITLE
Belt's Give Permanent Talisman slots and Duplicate Talisman items

### ISSUE THREAD

**Issue by RobertHDPotatoes** [SSKirillSS/relics#49]
This seems to be an incompatibility with a mod I have installed in my modpack, because it does not happen on a client with just curios and relics.

The Bug: When I create a new world in creative, if I equip a belt and something in a talisman slot, then remove my belt, the talisman slots are NOT removed, and it duplicates any items currently in my talisman slots.

Forge Version: 36.2.22
Minecraft Version: 1.16.5
Relics Version: 0.3.1
Curios Version: 4.0.6.3

Latest log: https://pastebin.com/xMFhAEUg

**Comment by SSKirillSS** [comment]
Hi. It doesn't seem like an issue of Relics mod. It seems more like an issue of CuriosAPI, but, I think, it already should be fixed. Update version of your CuriosAPI.

Btw Relics will change slot growing/shrinking mechanic too soon.

**Comment by RobertHDPotatoes** [comment]
You are correct, it has been fixed in the latest version of curios.
