### ISSUE TITLE
Game Crashes when looking at some relics in a chest

### ISSUE THREAD

**Issue by RobertHDPotatoes** [SSKirillSS/relics#50]
I was testing the new update in my modpack and my game crashed when looking at some curios I had in a chest.

Minecraft Version: 1.16.5
Forge Version: 36.2.22
Curios Version: 14.0.6.8
Relics Version: 0.3.2.1

Latest Log: https://pastebin.com/fNpR0e0k

**Comment by RobertHDPotatoes** [comment]
So after some testing it appears to crash because I assigned the Curio "nameless_trinkets:sleeping_pills" and the Curio "nameless_trinkets:tick" to the "Curio" slot in my modpack. Hopefully that helps with diagnosing the issue.

**Comment by SSKirillSS** [comment]
Hey. Thanks for the info. Fixed in https://github.com/SSKirillSS/relics/commit/ee06fef544a216b9d47324cce4a1a6e658a49590

Will be implemented in the next mod release

**Comment by SSKirillSS** [comment]
Done. You can download it **[here](https://www.curseforge.com/minecraft/mc-mods/relics-mod/files/3587815)**.
