### ISSUE TITLE
LegendaryTooltips Partially Overlay on top of Relics borders

### ISSUE THREAD

**Issue by RobertHDPotatoes** [SSKirillSS/relics#61]
Issue:
By default when installing LegendaryTooltips, all items in Minecraft classified as having the "Uncommon", "Rare", or "Epic" rarities are granted a default border, respective of their rarity. These default borders overlay partially on top of Relics custom borders, as shown in the attached screenshot. Items like relics:leather_belt are unaffected because that item does not have a rarity, and is not given a border by LegendaryTooltips, but an item like relics:spore_sack will have the "Uncommon" rarity border overlaying on top of Relics border. Players *could* remove LegendaryTooltips default rarity border entries, but that almost defeats the purpose of having LegendaryTooltips. 

Minecraft Version: 1.16.5
Forge Version: 36.2.22
Relics Version: 0.3.4.1
LegendaryTooltips Version: 1.1.5

![image](https://user-images.githubusercontent.com/72235443/151852644-9cad7c07-5971-424e-ae8c-d32d674fab64.png)

**Comment by AHilyard** [comment]
@RobertHDPotatoes Sorry for the misunderstanding, this is an issue that LegendaryTooltips will have to fix.  Could you repost this issue there? https://github.com/AHilyard/LegendaryTooltips/issues

**Comment by RobertHDPotatoes** [comment]
@AHilyard Whoops, that's what I get for trying to do things too fast haha. I thought your other comment said to post it to Relics github, not LegendaryTooltips... My bad haha. Will post to LegendaryTooltips ASAP, sorry.
