### ISSUE TITLE
Arrow Quiver Activated Ability Doesn't Work On Vanilla Bow When COFHCore Present

### ISSUE THREAD

**Issue by Trainerredstone7** [SSKirillSS/relics#62]
Relics version: 0.3.4
CuriosAPI version: 1.16.5-4.0.8.0
COFHCore version: 1.4.2.9

Since COFHCore also cancels the ArrowLooseEvent (but with a higher priority), the Arrow Quiver's activated ability won't trigger when you fire an arrow from a vanilla minecraft bow (or any other bow with COFH's BOW_ITEM_CAPABILITY).

**Comment by SSKirillSS** [comment]
Should be fixed since 1.18.2 release of the mod.
