### ISSUE TITLE
Jellyfish Necklace Magic Resistance Calculated Incorrectly

### ISSUE THREAD

**Issue by Trainerredstone7** [SSKirillSS/relics#63]
Instead of multiplying the incoming magic damage by (1-magic resistance), the magic damage is multiplied by the magic resistance value. This means with the default config, the jellyfish necklace (with +25% magic resistance) reduces magic damage by 75% instead of 25%. Not a gamebreaking bug but a little confusing.

**Comment by SSKirillSS** [comment]
Hey. Thanks for the info. Fixed for 1.16.5: https://www.curseforge.com/minecraft/mc-mods/relics-mod/files/3722387

Fix for 1.18.x will be released later when the major update will be finished.
