### ISSUE TITLE
Compability with Corpse mod

### ISSUE THREAD

**Issue by MiniRaptor** [SSKirillSS/relics#64]
It would be very convenient and cool if the mod had compatibility with Corpse mod, because it is inconvenient to manually put on the loot every time after death. 

Or you can just make it equiping with using Shift + Left Mouse Button

**Comment by SSKirillSS** [comment]
Hey. This thing can be added in the CuriosAPI, not Relics. Because CuriosAPI handles these custom slots, which you can use to equip relics.
