### ISSUE TITLE
squires bag does what?

### ISSUE THREAD

**Issue by Narsayden** [SSKirillSS/relics#68]
cant find a way to 'use' it, it has no keybind, nor does it show up in the wiki page...basically a useless item at this point?

**Comment by SSKirillSS** [comment]
Hi. It grants some additional slots. Read the relic description.

**Comment by Narsayden** [comment]
> Hi. It grants some additional slots. Read the relic description.

Alright thanks, I thought because it was a 'bag' you could use it for extra inventory, my bad
