### ISSUE TITLE
Lag on inventory tick

### ISSUE THREAD

**Issue by someaddons** [SSKirillSS/relics#69]
Some items try to get their owner on tick, but end up creating stacktraces each tick which is rather laggy and likely not intended

![image](https://user-images.githubusercontent.com/38401808/158188658-f6736ada-d56c-447b-9716-7b0c3bf5b9df.png)
https://spark.lucko.me/oaXGyfiWC8

relics-0.3.4.1
forge 1.18.1

**Comment by SSKirillSS** [comment]
It shouldn't be an issue anymore since recent version of 1.16.x Relics.
