### ISSUE TITLE
Delay Ring 

### ISSUE THREAD

**Issue by DoctorMage** [SSKirillSS/relics#71]
The delay ring has a bug in which it can activates itself meaning as long as a player has it equipped their immortal and can not be killed as well as the ring being able to survive /kill their is no way of killing a player who has it equipped

Video of issue
https://youtu.be/rG5O3A3_O_s

Another thing to note its been like this since 0.3.4 but was fine in 0.3.3

Mods
relics-0.3.4.1
curios-forge-1.16.5-4.0.8.1
logs
[latest.log](https://github.com/SSKirillSS/relics/files/8354878/latest.log)

**Comment by SSKirillSS** [comment]
Hey. Thanks for the info. Fixed for 1.16.5: https://www.curseforge.com/minecraft/mc-mods/relics-mod/files/3722387

Fix for 1.18.x will be released later when the major update will be finished.
