### ISSUE TITLE
Infinity Ham

### ISSUE THREAD

**Issue by DoctorMage** [SSKirillSS/relics#72]
Infinity Ham is not using durabillity

Mods
relics-0.3.4.2
curios-forge-1.16.5-4.0.8.1
[latest.log](https://github.com/SSKirillSS/relics/files/8627928/latest.log)
https://streamable.com/5agsq6

**Comment by SSKirillSS** [comment]
Yea. Atm durability doesn't affect items, that cannot be equipped in the CuriosAPI slots. So, not a bug.
