### ISSUE TITLE
Relic Durability

### ISSUE THREAD

**Issue by cleo994** [SSKirillSS/relics#73]
Items have durability after disabling it in the config.

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/168120936-8cba0550-0204-483d-8d28-3a89d67db44e.png)
Confirmed...

**Comment by SSKirillSS** [comment]
Fixed in https://github.com/SSKirillSS/relics/commit/9c7b920ab520f6f8718376ed5919a2c195d3f6dc
