### ISSUE TITLE
relics-1.16.5-0.3.4.3.jar Drowned Belt Riptide Boost Doesn't Work

### ISSUE THREAD

**Issue by God-follower101** [SSKirillSS/relics#74]
Playing on a mod pack, everything else is working fine but when I tried to use riptide with the Drowned belt it didn't work outside of water as the description says. 

I tried attaching the modpack but github doesn't support file folders like the mods folder is
edit: here is link 
https://www.dropbox.com/sh/60gyx2plhegxz81/AAAccoZrVazG6rZszfzJOy3ia?dl=0

**Comment by SSKirillSS** [comment]
Hi. I already know about this issue but don't know which mod in modpack can cause it.

Try to remove one-by-one mods from your modpack (make a backup or just switch to test world). Let me know in case you find something.
