### ISSUE TITLE
Arrows shot with Arrow Quiver's ability can always be picked up, even if the bow has infinite enchant

### ISSUE THREAD

**Issue by LTCatt** [SSKirillSS/relics#75]
![image](https://user-images.githubusercontent.com/40348278/168218034-5e739ea9-3bb3-44f3-bd84-853c5155bea3.png)
1.16

**Comment by SSKirillSS** [comment]
Fixed in https://github.com/SSKirillSS/relics/commit/631c67a40c276c74392cb86b38e7c48c2aebe4ca
