### ISSUE TITLE
Tooltip's border overlaps with Legendary Tooltip mod

### ISSUE THREAD

**Issue by LTCatt** [SSKirillSS/relics#76]
![T7(I29_ C~JON8UYCWITTEL](https://user-images.githubusercontent.com/40348278/168221281-70921af2-9dc4-4c48-b851-451743257444.png)
Maybe add a configuration that turns on or off custom borders?

**Comment by Aethamus** [comment]
In the Legendary Tooltips config you can add the relics mod like this: blacklist = ["@relics"]

**Comment by LTCatt** [comment]
Uh, I was trying to use Legendary Tooltips' border instead of Relics' to ensure visual consistency... I've solved it with mixin...
