### ISSUE TITLE
Ice Skates' speed was increased by 110% instead of 10%

### ISSUE THREAD

**Issue by LTCatt** [SSKirillSS/relics#77]
![image](https://user-images.githubusercontent.com/40348278/168231997-b5b02a7e-e2c0-4d3e-a03d-0e9b6ed34794.png)
![image](https://user-images.githubusercontent.com/40348278/168232177-5f953549-ba02-4875-a0ac-1df79e4beecb.png)
The actual test speed increased by 110% (to 2.1 times), so there is a mistake in the description or value...

**Comment by SSKirillSS** [comment]
Fixed in https://github.com/SSKirillSS/relics/commit/7cd6e031c4fc3012ba29bb7f30fea59ec4f77c22
