### ISSUE TITLE
Ice breaker and delay ring don't seem to work?

### ISSUE THREAD

**Issue by LTCatt** [SSKirillSS/relics#78]
Uh, sorry, I'm not sure if I'm having trouble or what, but I can't activate ice breaker's active skill, and delay ring doesn't slow down the damage taken. I'm not sure if this is a bug...
If you can, could you tell me the exact usage of these two items?
I am testing these items one by one to determine which items to add to my modpack. And this mod is really great :D
I may have turned in a few too many issues today, sorry......

**Comment by SSKirillSS** [comment]
Ice Breaker: You must hold [Shift] when you fall. Fall distance should be more than 3 blocks. On impact, relic deals damage to all entities around based on your total fall distance.
Delay Ring: When you get a critical hit, relic starts timer for 10 seconds. Til timer ends, relic will prevent all your damage and healing, then calculate it (heal will be doubled) and if total value is higher than 0 - your life will be saved. Example:
You got 20 damage and 12 heal:
0 - 20 = -20;
-20 + 12 * 2 = 4;
After timer stop, your health will be set to 4 and your life will be saved. Another example:
You got 20 damage and 5 heal:
0 - 20 = -20;
-20 + 5 * 2 = -10;
-10 < 0, so, you will die after timer stop.
