### ISSUE TITLE
1.16 spatial_sign is not working if the points of lvl is clear.

### ISSUE THREAD

**Issue by seal1204** [SSKirillSS/relics#81]
![image](https://user-images.githubusercontent.com/106885393/172021234-1e61066c-41a0-4e4f-9ec6-30cebeac3a00.png)
it wont work if the xp bar looks like this.

**Comment by SSKirillSS** [comment]
Can't reproduce. Works fine for me.

Probably issue may appear after /experience set command, it a bit broken in vanilla. Better to use /experience add.
