### ISSUE TITLE
[BUG] Ghost Skin Talisman is freezing the game

### ISSUE THREAD

**Issue by IamRyan30** [SSKirillSS/relics#84]
Mc: 1.16.5
Forge: 36.2.33
Relics: relics-1.16.5-0.3.4.3.jar
Curios: curios-forge-1.16.5-4.0.8.2.jar
ImprovedMobs: improvedmobs-1.16.5-1.10.13.jar

For some players, while they're wearing a Ghost Skin Talisman there's a chance that their game will freeze when they get shot with an arrow, either by a pillager, or by another player.
Not sure, but I think this might be related to the Improved mobs mod? This issue is kinda hard to reproduce as it happens only to some players. Also, there will be no crash on the logs.
Without the `Ghost Skin Talisman`, this doesn't seem to happen.

**Comment by IamRyan30** [comment]
Update: Apparently, the Piercing enchantment breaks the Talisman.

**Comment by SSKirillSS** [comment]
Fixed in https://github.com/SSKirillSS/relics/commit/4295baac8086fb403dd66834b6102558125a778d
