### ISSUE TITLE
Animations not working

### ISSUE THREAD

**Issue by DoctorMage** [SSKirillSS/relics#86]
Mods involved

CodeChickenLib-1.16.5-4.0.7.445-universal.jar
relics-1.16.5-0.3.4.3.jar
magnesium-1.5

Forge Version : 36.2.34

If codechickenlib is an instance with magensium and relics it causes the animations of the relics to no longer be enabled unsure were to reports this
https://streamable.com/uyvjra
https://streamable.com/8p3kkj

**Comment by SSKirillSS** [comment]
Relics uses vanilla .mcmeta animations, so it's issue of mods you're using.
