### ISSUE TITLE
Duplication Bug: Domestic Inovation colars wtih enchants can be replaced infintently

### ISSUE THREAD

**Issue by Shibva** [SSKirillSS/relics#92]
This bug is a interaction Between Relics and Dommestic Innovation. 

The mod adds colars that can be enchanted with certain enchants to add benefits to your pets, however, while toying around I found a bit of an issue with it and in turn discovered by shear accident that I can duplicate the enchantment collar it had on with the horse flute and then change it out each time to get the same enchants for free

my suggestion to fix this is to have the data that's on the bound horse act like with inventory slots or something

**Comment by SSKirillSS** [comment]
Can you provide a video-showcase of this bug?

**Comment by Shibva** [comment]
issue found to be irrelivent and caused by another interaction not involving relics
