### ISSUE TITLE
Managing to damage yourself causes Midnight Cloak to target your UUID

### ISSUE THREAD

**Issue by XenoStone1009** [SSKirillSS/relics#94]
So I've found that managing to damage myself eg. by Pneumaticraft Micromissiles will cause the cloak to forever be tied to your own Player UUID.

Presumably having another player wear it and walk out of the radius is a solution, but for single player it might be worth coding that the wearer and target UUID cannot be the same or clear the target if they match.

I am using Relics 0.4.1.11 on minecraft 1.19.2
(pneumaticraft version is 4.1.3-15 if you need that too)

**Comment by SSKirillSS** [comment]
Thanks for the info! Fixed and will be uploaded to CF soon.
