### ISSUE TITLE
[Bug 1.19.2] Crash on Startup

### ISSUE THREAD

**Issue by SaltSouls** [SSKirillSS/relics#95]
I'm not exactly sure if this is an incompatibility with another mod in the list, but every now and again when starting the game it will just crash. It is something during the `sided_setup` event that is apparently going wrong. I have a feeling it is the way relics is registering something is causing an incompatibility with the way another mod is trying to register stuff, though that's just a guess.

Minecraft: 1.19.2
Forge: 43.2.6
Relics: 1.19.2-0.4.1.11

Log: [latest.log](https://github.com/SSKirillSS/relics/files/10836611/latest.log)
Crash Log: [crash.txt](https://github.com/SSKirillSS/relics/files/10836607/crash-2023-02-26_22.09.37-fml.txt)

**Comment by SSKirillSS** [comment]
Hi. Afaik there are 2 possible issues:
1. You have multiple versions of Relics installed
2. You have another mod that loads before Relics and adds animation tag with id "pieces".

idk which mod is it, so... I can't tell you more about this
