### ISSUE TITLE
The star count for certian relics "cooldowns" is backwards

### ISSUE THREAD

**Issue by DraTrav** [SSKirillSS/relics#98]
The Star count gets higher for certain relics when the cool down timer gets longer. For example the Drowned belt trident cool down gives you more stars for the longer the cool down is when it should be the opposite. This apply for the shadow glaive as well. This also applies to the rage globes "Berserk rage" incoming damage multiplier, where would expect lower is better

**Comment by SSKirillSS** [comment]
Thanks for the info! Fixed and will be uploaded to CF soon.
