### ISSUE TITLE
[1.19.2] Infinity Ham Alchemy Ability Ignores Duration Stat

### ISSUE THREAD

**Issue by gamrguy** [SSKirillSS/relics#99]
Title.
Infinity Ham's Alchemy ability always applies 100 ticks of potion effect rather than the stated duration.

To replicate:
1. Get an Infinity Ham with Lv. 0 Alchemy. It should apply 5s instead of whatever its roll is.
2. Get an Infinity Ham with Lv. 10 Alchemy. It should apply 5s instead of whatever its roll is.

https://github.com/SSKirillSS/relics/blob/e2cd06408f8400b81bb2413ddebe32e20300c0cb/src/main/java/it/hurts/sskirillss/relics/items/relics/InfinityHamItem.java#L159

Related: Infinity Ham ignores whether the incoming potion effect is intended to be instant.
Instant Health and Instant Damage are thus far more effective than normal.

**Comment by SSKirillSS** [comment]
Thanks for the info. Will be fixed in the next update.
